# Generated by Django 3.2.2 on 2021-12-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('so', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('contrasenia', models.CharField(max_length=255)),
            ],
        ),
    ]
