# Generated by Django 3.2.2 on 2021-12-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_Cripto5_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informacion',
            new_name='Pdf',
        ),
    ]
